parameters:
    oro_querydesigner.form.type.aggregate_choice.class:              Oro\Bundle\QueryDesignerBundle\Form\Type\AggregateChoiceType
    oro_querydesigner.form.type.sorting_choice.class:                Oro\Bundle\QueryDesignerBundle\Form\Type\SortingChoiceType
    oro_querydesigner.form.type.query_designer_column.class:         Oro\Bundle\QueryDesignerBundle\Form\Type\ColumnType
    oro_querydesigner.form.type.query_designer_filter.class:         Oro\Bundle\QueryDesignerBundle\Form\Type\FilterType
    oro_querydesigner.form.type.query_designer_grouping.class:       Oro\Bundle\QueryDesignerBundle\Form\Type\GroupingType

services:
    oro_querydesigner.form.type.aggregate_choice:
        class: %oro_querydesigner.form.type.aggregate_choice.class%
        tags:
            - { name: form.type, alias: oro_aggregate_choice }

    oro_querydesigner.form.type.sorting_choice:
        class: %oro_querydesigner.form.type.sorting_choice.class%
        tags:
            - { name: form.type, alias: oro_sorting_choice }

    oro_querydesigner.form.type.query_designer_column:
        class: %oro_querydesigner.form.type.query_designer_column.class%
        tags:
            - { name: form.type, alias: oro_query_designer_column }

    oro_querydesigner.form.type.query_designer_filter:
        class: %oro_querydesigner.form.type.query_designer_filter.class%
        tags:
            - { name: form.type, alias: oro_query_designer_filter }

    oro_querydesigner.form.type.query_designer_grouping:
        class: %oro_querydesigner.form.type.query_designer_grouping.class%
        tags:
            - { name: form.type, alias: oro_query_designer_grouping }
