query_designer:
    grouping:
        exclude: [{type: text}, {type: array}, {type: object}]

    filters:
        string:
            applicable: [{type: string}, {type: text}]
            type:       string
            query_type: [all]
        number:
            applicable: [{type: integer}, {type: smallint}, {type: bigint}, {type: decimal}, {type: float}, {type: money}]
            type:       number
            query_type: [all]
        date:
            applicable: [{type: date}]
            type:       date
            query_type: [all]
        datetime:
            applicable: [{type: datetime}]
            type:       datetime
            query_type: [all]
        boolean:
            applicable: #[{type: boolean}]
                - {type: boolean}
#START for testing, remove before merge
                - {entity: OroCRM\Bundle\ContactBundle\Entity\ContactAddress, field: country000}
                - {entity: Oro\Bundle\AddressBundle\Entity\AbstractAddress, field: country111}
#END
            type:       boolean
            query_type: [all]
        percent:
            applicable: [{type: percent}]
            type:       percent
            query_type: [all]
