config:
    paths:
        'oroquerydesigner/js/query-designer': 'bundles/oroquerydesigner/js/query-designer.js'
        'oroquerydesigner/js/query-designer/util': 'bundles/oroquerydesigner/js/query-designer/util.js'
        'oroquerydesigner/js/query-designer/function-manager': 'bundles/oroquerydesigner/js/query-designer/function-manager.js'
        'oroquerydesigner/js/query-designer/abstract-view': 'bundles/oroquerydesigner/js/query-designer/abstract-view.js'
        'oroquerydesigner/js/query-designer/column-selector-view': 'bundles/oroquerydesigner/js/query-designer/column-selector-view.js'
        'oroquerydesigner/js/query-designer/column/collection': 'bundles/oroquerydesigner/js/query-designer/column/collection.js'
        'oroquerydesigner/js/query-designer/column/model': 'bundles/oroquerydesigner/js/query-designer/column/model.js'
        'oroquerydesigner/js/query-designer/column/view': 'bundles/oroquerydesigner/js/query-designer/column/view.js'
        'oroquerydesigner/js/query-designer/grouping/view': 'bundles/oroquerydesigner/js/query-designer/grouping/view.js'

        'oroquerydesigner/js/condition-builder': 'bundles/oroquerydesigner/js/condition-builder.js'
        'oroquerydesigner/js/field-condition': 'bundles/oroquerydesigner/js/field-condition.js'
