parameters:
    oro_querydesigner.querydesigner.manager.class:        Oro\Bundle\QueryDesignerBundle\QueryDesigner\Manager
    oro_querydesigner.provider.resolver.class:            Oro\Bundle\QueryDesignerBundle\Provider\SystemAwareResolver

services:
    oro_querydesigner.querydesigner.manager:
        class: %oro_querydesigner.querydesigner.manager.class%
        arguments:
            - []
            - @oro_querydesigner.provider.resolver

    oro_querydesigner.provider.resolver:
        class: %oro_querydesigner.provider.resolver.class%
        arguments:
            - @service_container
