parameters:
    oro_query_designer.query_designer.manager.class:          Oro\Bundle\QueryDesignerBundle\QueryDesigner\Manager
    oro_query_designer.provider.resolver.class:              Oro\Bundle\QueryDesignerBundle\Provider\SystemAwareResolver
    oro_query_designer.grid.extension.orm_datasource.class:  Oro\Bundle\QueryDesignerBundle\Grid\Extension\OrmDatasourceExtension

services:
    oro_query_designer.query_designer.manager:
        class: %oro_query_designer.query_designer.manager.class%
        arguments:
            - []
            - @oro_query_designer.provider.resolver
            - @translator

    oro_query_designer.provider.resolver:
        class: %oro_query_designer.provider.resolver.class%
        arguments:
            - @service_container

    oro_query_designer.grid.extension.orm_datasource:
        class: %oro_query_designer.grid.extension.orm_datasource.class%
        arguments:
            - @oro_query_designer.query_designer.manager
        tags:
            - { name: oro_datagrid.extension }
