oro_qb_field_api:
    resource: "@OroQueryDesignerBundle/Controller/Api/Rest/QueryDesignerEntityFieldController.php"
    type:     rest

oro_qb_entity_api:
    resource: "@OroQueryDesignerBundle/Controller/Api/Rest/QueryDesignerEntityController.php"
    type:     rest
